config/routes.rb
Rails.application.routes.draw do
  get '/view_as_admin' => 'admin/members#view_as_admin'
  get '/view_as_reader' => 'admin/members#view_as_reader'

  resources :reservations, only: [:show, :index]
  resources :check_out, only: [:index, :edit, :update]
  resources :check_in, only: [:index, :edit, :update]

  resources :members, except: [:show, :destroy]
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  resources :items do
    resources :reservations
    collection do
      get :added_by_me
    end
  end
  devise_for :users
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Example resource route within a namespace:
  namespace :admin do
      # Directs /admin/products/* to Admin::ProductsController
      # (app/controllers/admin/products_controller.rb)
    resources :members, only: [:index, :show]
    resources :reservations, only: [:index]
  end
end

app/controllers/check_in_controller.rb
class CheckInController < ApplicationController
  def index
    @reservations = Reservation.not_checked_in
  end

  def edit
    @reservation = Reservation.find params[:id]
    if @reservation.checked_in?
      flash[:error] = "This reservation has been checked in before (by #{@reservation.checked_out_by})"
      redirect_to @reservation
    end
  end

  def update
    @reservation = Reservation.find params[:id]
    @reservation.check_in_notes = params[:reservation][:check_in_notes]
    @reservation.check_in_by!(current_user)
    if @reservation.errors.empty?
      flash[:success] = "Checked in successfully"
      redirect_to @reservation.item
    else
      render action: 'edit'
    end
  end
end

app/helpers/check_in_helper.rb
module CheckInHelper
end

app/views/check_in/_form_body.html.slim
= render 'items/item_preview', item: f.object.item
p.reservation-member
  span.text-muted> Borrower:
  = f.object.member

app/views/check_in/edit.html.slim
h1 Check In

.row: .col-sm-4
  .panel.panel-primary
    .panel-heading
      h4.panel-title
        span.label.label-info.panel-title => @reservation.item.kind.upcase
        | Return
    = simple_form_for @reservation, url: check_in_path(@reservation) do |f|
      .panel-body
        = render 'check_in/form_body', f: f
        - if @reservation.check_out_notes.present?
          .alert.alert-warning
            strong> Check-out notes:
            = @reservation.check_out_notes
        = f.input :check_in_notes
      .panel-footer
        = f.submit "Return!", class: 'btn btn-success btn-lg btn-block', data: {disable_with: "Returning..."}

app/views/check_in/index.html.slim
h1 Pending Reservations

table.table
  thead
    tr
      th Item
      th Borrow
      th Due date
  tbody
    - @reservations.each do |reservation|
      tr
        td = reservation.item.title
        td = reservation.member.full_name
        td.timestamp = reservation.due_date.to_s(:day_long)
        td
          = link_to "Check In", edit_check_in_path(reservation), class: 'btn btn-primary'