config/routes.rb
Rails.application.routes.draw do
  get '/view_as_admin' => 'admin/members#view_as_admin'
  get '/view_as_reader' => 'admin/members#view_as_reader'

  resources :reservations, only: [:show, :index]
  resources :check_out, only: [:index, :edit, :update]
  resources :check_in, only: [:index, :edit, :update]

  resources :members, except: [:show, :destroy]
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  resources :items do
    resources :reservations
    collection do
      get :added_by_me
    end
  end
  devise_for :users
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Example resource route within a namespace:
  namespace :admin do
      # Directs /admin/products/* to Admin::ProductsController
      # (app/controllers/admin/products_controller.rb)
    resources :members, only: [:index, :show]
    resources :reservations, only: [:index]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :subject
  belongs_to :school_level
  belongs_to :category

  extend Enumerize
  enumerize :kind, in: [:book, :media, :unknown], default: :book

  searchable do
    text :title, boost: 5
    text :kind
    text :author
    text :summary
    integer :number_of_pages
    text :code
    text :publisher
    time :created_at

    # for facets
    string(:format) { kind }
    string :author
    string :publisher
    string(:subject) { subject.try(:name) }
    string(:category) { category.try(:name) }
    string(:school_level) { school_level.try(:name) }
  end

  validates :title, :quantity, presence: true
  # validates :code, uniqueness: {allow_blank: false}, presence: true

  has_many :reservations, dependent: :destroy

  before_save :check_available_count

  # override to allow creating subjects on the fly
  def subject_id=(value)
    if Subject.find_by_id(value)
      super
    elsif (s = Subject.where(name: value).first_or_create).id
      super(s.id)
    else
      super
    end
  end

  def school_level_id=(value)
    if SchoolLevel.find_by_id(value)
      super
    elsif (s = SchoolLevel.where(name: value).first_or_create).id
      super(s.id)
    else
      super
    end
  end

  def category_id=(value)
    if Category.find_by_id(value)
      super
    elsif (s = Category.where(name: value).first_or_create).id
      super(s.id)
    else
      super
    end
  end

  def added_by
    User.find_by_id(added_by_id)
  end

  # rails_admin_import
  def before_import_save(row, map)
    # Your custom special sauce
  end

  def after_import_save(row, map)
    # Your custom special sauce
  end

  def check_available_count
    self.available_count = compute_remaining
  end

  def compute_remaining
    quantity - reservations.borrowed.count
  end

  def to_s
    title
  end

  def hard_tags
    hash = {}
    %w(subject category school_level).each do |field|
      val = send(field)
      hash[field] = val if val.present?
    end
    hash
  end

  def self.facet_fields
    %i(format author publisher subject category school_level)
  end

  def self.find_authors(name = nil)
    search do
      with(:author, name) if name.present?
      facet(:author)
    end.facet(:author).rows.map(&:value)
  end

  def self.find_publishers(name = nil)
    search do
      with(:publisher, name) if name.present?
      facet(:publisher)
    end.facet(:publisher).rows.map(&:value)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!, only: [:added_by_me]

  def added_by_me
    @items = current_user.added_items.page(params[:page]).per(params[:per_page])
  end

  def index
    @search = Item.search do
      fulltext params[:search]
      order_by(:created_at, :desc)

      filters = []
      Item.facet_fields.each do |field|
        if params[field].present?
          filters << with(field, params[field])
        end
      end

      Item.facet_fields.each do |field|
        facet(field, exclude: filters)
      end

      paginate(page: params[:page], per_page: params[:per_page])
    end

    @items = @search.results
    @preloader = true
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new item_params
    if @item.save
      redirect_to @item
    else
      render action: 'new'
    end
  end

  def edit
    @item = Item.find params[:id]
    authorize @item
  end

  def update
    @item = Item.find params[:id]
    if @item.update_attributes item_params
      redirect_to @item
    else
      render action: 'edit'
    end
  end

  def show
    @item = Item.find params[:id]
  end

  private

  def item_params
    params.require(:item).permit!
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def searched_item_facets
    Item.facet_fields.select{|field| params[field]}
  end

  def query_params
    params.except(:action, :controller)
  end
end

app/views/items/_available_count.html.slim
.available-counter.text-smaller class=(item.available_count.zero? ? 'text-danger' : 'text-success')
  => item.available_count
  ' available
  ' (#{item.quantity} total)

app/views/items/_form.html.slim
= simple_form_for item do |f|
  .panel-body
    - if f.object.filepicker_url?
      .thumbnail
        = filepicker_image_tag f.object.filepicker_url, w: 320, fit: 'clip'
    = f.filepicker_field :filepicker_url, class: 'btn btn-default', button_text: "Change Image"
    .text-muted
      | (after selecting an image, remember to save changes)
    = f.input :title
    .row
      .col-sm-6
        = f.input :kind, label: 'Format'
      .col-sm-6
        = f.input :quantity
    .row
      .col-sm-6
        = f.association :school_level, input_html: {class: 'selectize'}
      .col-sm-6
        = f.association :subject, input_html: {class: 'selectize'}
    = f.association :category, input_html: {class: 'selectize'}
    = f.input :author, collection: Item.find_authors, input_html: {class: 'selectize'}
    = f.input :summary
    .row
      .col-sm-6
        = f.input :number_of_pages
      .col-sm-6
        = f.input :code
    = f.input :publisher, collection: Item.find_publishers, input_html: {class: 'selectize'}
  .panel-footer
    = f.submit nil, class: 'btn btn-primary btn-block btn-lg'

= filepicker_js_include_tag

coffee:
  $('select.selectize').each ->
    $(this).selectize({create: true})

app/views/items/_item_extras.html.slim
.item-extras
  .item-summary
    strong> Summary:
    = simple_format item.summary

app/views/items/_item_preview.html.slim
.item-preview
  h4.list-group-item-heading
    = link_to item.title, item
  .list-group-item-text
    .item-author
      span.text-muted by
      =< link_to item.author, items_path(query_params.merge(author: item.author))
    p.item-publisher
      =< link_to item.publisher, items_path(query_params.merge(publisher: item.publisher))

app/views/items/_items.html.slim
= paginate items
.page-entries-info style="margin-left:10px"
  = page_entries_info items

/= render 'items/v1/items'
#items-container
  - items.each do |item|
    .item
      = link_to item do
        - if item.filepicker_url?
          = filepicker_image_tag item.filepicker_url, w: 150, fit: 'clip'
        - else
          = image_tag "http://placehold.it/167x127&text=No+Image!", class: 'list-group-image'
      .caption
        = render 'item_preview', item: item
        = render 'available_count', item: item

coffee:
  window.ItemsJs.setupItems()

app/views/items/_list_vs_grid.html.slim
.btn-group
  a#list.btn.btn-default
    span.glyphicon.glyphicon-th-list>
    span.hidden-xs List
  a#grid.btn.btn-default.active
    span.glyphicon.glyphicon-th>
    span.hidden-xs Grid

app/views/items/_search_filter.html.slim
.panel-group
  - Item.facet_fields.each do |field|
    .panel class=(params[field] ? 'panel-info' : 'panel-default')
      .panel-heading.collapse-toggle [
        data-toggle="collapse" data-target="#facet-#{field}" aria-expanded="true"
        class=('collapsed' unless params[field])
      ]
        h5.panel-title
          a href="#" data-no-turbolink="true" = field.to_s.humanize
      .panel-collapse.facet-content.collapse id="facet-#{field}" class=('in' if params[field])
        .panel-body
          ul.list-unstyled.facet-values style="margin-bottom:0"
            - search.facet(field).rows.sort_by(&:value).each do |row|
              li class=('active' if row.value == params[field])
                span.facet-label
                  => link_to row.value.presence || '(unknown)', url_for(query_params.merge(field => row.value))
                  - if row.value == params[field]
                    = link_to query_params.merge(field => nil), class: 'remove' do
                      span.glyphicon.glyphicon-remove
                      span.sr-only
                        | [remove]
                span.facet-count = row.count

app/views/items/added_by_me.html.slim
h1 Items added by you
.alert.alert-info
  | Thank you for helping us catalogue the items in the library.

= render 'items', items: @items

app/views/items/edit.html.slim
.row
  .col-sm-5.col-md-4
    - if @item.added_by == current_user
      .alert.alert-info
        button.close data-dismiss="alert" aria-label="Close"
          span aria-hidden="true"
          | &times;
        | You added this on #{@item.created_at.to_s(:am_pm_long)}
    .panel.panel-primary
      .panel-heading
        h1.panel-title Update Item
      = render 'form', item: @item

app/views/items/index.html.slim
h1 Catalogue

- if params[:search] || !searched_item_facets.empty?
  .well.well-sm
    .pull-right
      = link_to 'Start over', url_for(search: nil), class: 'btn btn-text btn-sm'
    | Searching for:
    span.btn.btn-text = params[:search]

    - searched_item_facets.each do |field|
      .btn-group
        span.btn.btn-default.btn-sm.disabled
          => field.to_s.humanize
          span.glyphicon.glyphicon-menu-right>
          span.text-primary = params[field]
        a.btn.btn-default.btn-sm.remove href=(url_for(field => nil))
          span.glyphicon.glyphicon-remove

/.pull-right
  = render 'list_vs_grid'

= render 'items', items: @items

app/views/items/new.html.slim
h1
.row
  .col-sm-6.col-md-5
    .panel.panel-primary
      .panel-heading
        h1.panel-title New Library Item
      = render 'form', item: @item

app/views/items/show.html.slim
.row.item
  .col-sm-4.no-padding
    .panel.panel-primary
      .panel-heading
        span.label.label-info.panel-title = @item.kind.upcase
        - if policy(:item).edit?
          =<> link_to 'edit', edit_item_path(@item), class: 'close'
      .panel-body
        .thumbnail
          = link_to @item do
            - if @item.filepicker_url?
              = filepicker_image_tag @item.filepicker_url, w: 320, fit: 'clip'
            - else
              = image_tag "http://placehold.it/100&text=No+Image!", class: 'list-group-image'
          .caption
            = render 'item_preview', item: @item
            = render 'available_count', item: @item
      .panel-footer
        = render 'item_extras', item: @item
      .panel-footer
        - @item.hard_tags.each do |k, v|
          div style="display:inline-block;white-space:nowrap"
            = fa_icon 'angle-left'
            span> #{k.humanize}:
            = link_to v, items_path(k => v.to_s)
            = fa_icon 'angle-right'

      .panel-footer
        - if @item.available_count <= 0
          button.btn.btn-disabled.btn-block title="Not available. Please wait until someone returns at least a copy." data-toggle="tooltip"
            | Out of stocked
        - else
          = reservation_link 'Reserve', 'reserved', new_item_reservation_path(@item)
  .col-sm-8
    = render 'reservations/reservations', reservations: @item.reservations, hide_item: true

javascript:
  $('[data-toggle="tooltip"]').tooltip()