config/routes.rb
Rails.application.routes.draw do
  get '/view_as_admin' => 'admin/members#view_as_admin'
  get '/view_as_reader' => 'admin/members#view_as_reader'

  resources :reservations, only: [:show, :index]
  resources :check_out, only: [:index, :edit, :update]
  resources :check_in, only: [:index, :edit, :update]

  resources :members, except: [:show, :destroy]
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  resources :items do
    resources :reservations
    collection do
      get :added_by_me
    end
  end
  devise_for :users
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Example resource route within a namespace:
  namespace :admin do
      # Directs /admin/products/* to Admin::ProductsController
      # (app/controllers/admin/products_controller.rb)
    resources :members, only: [:index, :show]
    resources :reservations, only: [:index]
  end
end

app/views/layouts/_admin_lis.html.slim
li = link_to "Superadmin", rails_admin_path
li = link_to "Manage Members", admin_members_path
li = link_to "Manage Reservations", admin_reservations_path

app/views/layouts/_head.html.slim
head
  meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
  title
    ' Rainbow
    - if ENV['SITE_NAME']
      ' - #{ENV['SITE_NAME']}
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/_main_body.html.slim
- if flash.present?
  - flash.each do |name, msg|
    p[class="alert #{flasherize name} fade in"] 
      button.close data-dismiss="alert"
        | &times;
      = msg
= yield

app/views/layouts/_navbar.html.slim
.navbar-header
  button.navbar-toggle.toggle-left.hidden-md.hidden-lg data-toggle="sidebar" data-target=".sidebar-left"
    span.icon-bar
    span.icon-bar
    span.icon-bar
  button.navbar-toggle.hide-sidebar-drawer.visible-md.visible-lg href="#"
    = fa_icon 'chevron-left lg'
  button.navbar-toggle.toggle-right data-toggle="sidebar" data-target=".sidebar-right"
    span.label
      = current_role
  a.navbar-brand href="/"
    = fa_icon 'university lg'
    span.brand-text.hidden-xs
      = ENV['SITE_NAME'] || 'Rainbow'

app/views/layouts/_right_sidebar.html.slim
ul.nav.navbar-stacked
  - if user_signed_in?
    li = link_to 'Account', edit_user_registration_path
    li = link_to 'Items I Added', added_by_me_items_path
    li = link_to 'My Reservations', reservations_path
    li = link_to "Logout", destroy_user_session_path
  - else
    li = link_to "Sign in", new_user_session_path

hr

- if current_admin
  ul.nav.navbar-stacked
    = render 'layouts/admin_lis'
    li
      - if current_role == 'admin'
        = link_to '/view_as_reader' do
          ' View As
          span.label.label-info reader
      - else
        = link_to '/view_as_admin' do
          ' View As
          span.label.label-default admin

app/views/layouts/_sidebar.html.slim
ul.nav.navbar-stacked style="margin-bottom:20px"
  li class=('active' if current_page?(items_path))
    = link_to items_path do
      span Catalogue
      =< fa_icon "book lg", class: 'pull-right'
  - if current_admin
    li class=('active' if current_page?(new_item_path))
      = link_to new_item_path do
        span New Book
        =< fa_icon "leanpub lg", class: 'pull-right'
    li
      = link_to admin_reservations_path(q: 'reserved') do
        span Check Out
        =< fa_icon "barcode lg", class: 'pull-right'
div style="padding-left: 5px; padding-right:5px"
  = render 'shared/search', path: items_path
  p
  - if @search
    = render 'items/search_filter', search: @search

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'
  body.dark-bg
    - if @preloader
      .preloader
    .navbar.navbar-inverse.navbar-fixed-top.navbar-static
      = render 'layouts/navbar'
    .container-fluid
      .row
        .col-xs-7.col-sm-3.col-md-3.sidebar.sidebar-left.sidebar-animate.sidebar-md-show
          = render 'layouts/sidebar'
        .main-body.col-xs-12.col-md-9.col-md-offset-3
          = render 'layouts/main_body'
        .col-xs-7.col-sm-3.col-md-3.sidebar.sidebar-right.sidebar-animate
          = render 'layouts/right_sidebar'
    .device-xs.visible-xs
    .device-sm.visible-sm
    .device-md.visible-md
    .device-lg.visible-lg